# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: publysher/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - rm -rf public
  - hugo --ignoreCache
  artifacts:
    paths:
    - public
  only:
  - gitlab_pages

test:
  script:
  - hugo
  except:
  - gitlab_pages
