---
MetaDataFormat: "yaml"
theme: "kjh"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
baseurl: "https://www.jonathangilligan.org/"
indexes:
  category: "categories"
title: "Jonathan Gilligan"
canonifyUrls: true
relativeUrls: true
enableRobotsTXT: true
menu:
  main:
      - Name: "What's New"
        URL: "/whats_new"
        Weight: 2
      - Name: "Research"
        URL: "/research"
        Weight: 3
      - Name: "Publications"
        URL: "/publications"
        Weight: 4
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 5
#      - Name: "Blog"
#        URL: "/blog"
#        Weight: 6
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
blackfriday:
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true
googleAnalytics: "UA-101117636-1"
params:
  AuthorName: "Jonathan Gilligan"
...
