---
MetaDataFormat: "yaml"
theme: "hugo-finisterre"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
baseurl: "https://www.jonathangilligan.org/"
indexes:
  category: "categories"
title: "Jonathan Gilligan"
copyright: "&copy; 2017 Jonathan Gilligan"
canonifyUrls: true
relativeUrls: true
enableRobotsTXT: true
ignoreFiles: [ "~$", "^\\.", "\\.#" ]
menu:
  main:
      - Name: "What's New"
        URL: "/whats_new"
        Weight: 2
      - Name: "Research"
        URL: "/research"
        Weight: 3
      - Name: "Publications"
        URL: "/publications"
        Weight: 4
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 5
#      - Name: "Blog"
#        URL: "/blog"
#        Weight: 6
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
blackfriday:
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true
googleAnalytics: "UA-101117636-1"
params:
  AuthorName: "Jonathan Gilligan"
  bio_name: "Jonathan Gilligan"
  bio_twitter: "jg_environ"
  math: false
  organization: "Vanderbilt University"
  avatar: "avatar.jpg"
  front_page_img: "jg/jg_sundarbans.jpg"
  email: "jonathan.gilligan@vanderbilt.edu"
  address:
    - "Department of Earth &amp; Environmental Sciences,"
    - "Vanderbilt University<br/>"
    - "2301 Vanderbilt PL,"
    - "PMB 351805,<br/>"
    - "Nashville,"
    - "TN"
    - "37235-1805"
  social:
    email:
      icon: "envelope"
      icon_pack: "fa"
      link: "mailto:jonathan.gilligan@vanderbilt.edu"
      text: "jonathan.gilligan@vanderbilt.edu"
    twitter:
      icon: "twitter"
      icon_pack: "fa"
      link: "https://twitter.com/jg_environ"
      text: "@jg_environ"
      on_site: "Twitter"
    github:
      icon: "github"
      icon_pack: "fa"
      link: "https://github.com/jonathan-g"
      text: "jonathan-g"
      on_site: "GitHub"
    orcid:
      icon: "orcid"
      icon_pack: "ai"
      link: "https://orcid.org/0000-0003-1375-6686"
      text: "0000-0003-1375-6686"
      site: "ORCID"
    ssrn:
      link: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=954061"
      text: "954061"
      site: "SSRN ID:"
    google_scholar:
      icon: "google-scholar"
      icon_pack: "ai"
      link: "https://scholar.google.com/citations?hl=en&user=B8RVAU0AAAAJ"
      text: "Google Scholar"
---
