---
MetaDataFormat: "yaml"
theme: "kjh"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
baseurl: "https://www.jgilligan.org/"
indexes:
  category: "categories"
title: "Jonathan Gilligan"
canonifyUrls: true
relativeUrls: true
enableRobotsTXT: true
menu:
  main:
      - Name: "Publications"
        URL: "/publications"
        Weight: 2
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 4
      - Name: "Blog"
        URL: "/blog"
        Weight: 5
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
blackfriday:
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true
params:
  AuthorName: "Jonathan Gilligan"
...
