# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Finisterre"
license = "MIT"
licenselink = "https://github.com/jonathan-g/hugo-finisterre/blob/master/LICENSE.md"
description = "A simple academic theme."
homepage = "https://github.com/jonathan-g/hugo-finisterre"
tags = ["academic", "portfolio", "personal", "student", "faculty", "university",
        "basic",
        "foundation", "Google Analytics",
        "Font awesome", "Academic icons"
        ]
features = ["academic profile",
            "publications", "research publication system", "bibliography",
            "projects",
            "teaching",
            "posts", "blog", "social",
            "Google Analytics",
            "Font awesome", "Academic icons",
            "font-awesome", "academic-icons",
            "fontawesome", "academicicons",
            "contact"
            ]
min_version = 0.21

[author]
  name = "Jonathan Gilligan"
  homepage = "https://www.jonathangilligan.org/"
